name: Close stale issues
on:
  schedule:
    - cron: "35 12 * * *"

jobs:
  close-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v7.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
